### ISSUE TITLE
meta.xml of idigbio dwca contains duplicate eventDate field

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/source-idigbio#1]
when importing a recent copy of idigbio dwca, I noticed that two eventDate fields are defined in meta.xml. @mjcollin @godfoder is this by design?

here's the error from dwca2parquet

```
Exception in thread "main" org.apache.spark.sql.AnalysisException: Duplicate column(s) : "http://rs.tdwg.org/dwc/terms/eventDate" found, cannot save to parquet format;
    at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation.checkConstraints(ParquetRelation.scala:196)
    at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation.dataSchema(ParquetRelation.scala:205)
    at org.apache.spark.sql.sources.HadoopFsRelation.schema$lzycompute(interfaces.scala:636)
```

and the associated meta.xml (see field 16 and 24 of "core" table):

``` xml
<archive xmlns="http://rs.tdwg.org/dwc/text/">

  <core encoding="utf-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files>
      <location>occurrence.csv</location>
    </files>
    <id index="0" />
    <field index="1" term="http://portal.idigbio.org/terms/barcodeValue"/>
    <field index="2" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/bed"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/catalogNumber"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/class"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/collectionCode"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/collectionID"/>
    <field index="8" term="http://portal.idigbio.org/terms/collectionName"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/recordedBy"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/vernacularName"/>
    <field index="11" term="http://rs.tdwg.org/dwc/terms/continent"/>
    <field index="12" term="http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters"/>
    <field index="13" term="http://rs.tdwg.org/dwc/terms/country"/>
    <field index="14" term="http://portal.idigbio.org/terms/isoCountryCode"/>
    <field index="15" term="http://rs.tdwg.org/dwc/terms/county"/>
    <field index="16" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
    <field index="17" term="http://portal.idigbio.org/terms/dateModified"/>
    <field index="18" term="http://portal.idigbio.org/terms/dataQualityScore"/>
    <field index="19" term="http://rs.tdwg.org/dwc/terms/earliestAgeOrLowestStage"/>
    <field index="20" term="http://rs.tdwg.org/dwc/terms/earliestEpochOrLowestSeries"/>
    <field index="21" term="http://rs.tdwg.org/dwc/terms/earliestEraOrLowestErathem"/>
    <field index="22" term="http://rs.tdwg.org/dwc/terms/earliestPeriodOrLowestSystem"/>
    <field index="23" term="http://portal.idigbio.org/terms/etag"/>
    <field index="24" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
    <field index="25" term="http://rs.tdwg.org/dwc/terms/family"/>
    <field index="26" term="http://rs.tdwg.org/dwc/terms/fieldNumber"/>
    <field index="27" term="http://portal.idigbio.org/terms/flags"/>
    <field index="28" term="http://rs.tdwg.org/dwc/terms/formation"/>
    <field index="29" term="http://rs.gbif.org/terms/1.0/cannonicalName"/>
    <field index="30" term="http://rs.gbif.org/terms/1.0/genus"/>
    <field index="31" term="http://rs.gbif.org/terms/1.0/specificEpithet"/>
    <field index="32" term="http://rs.gbif.org/terms/1.0/taxonID"/>
    <field index="33" term="http://rs.tdwg.org/dwc/terms/genus"/>
    <field index="34" term="http://portal.idigbio.org/terms/geoPoint"/>
    <field index="35" term="http://portal.idigbio.org/terms/geoShape"/>
    <field index="36" term="http://rs.tdwg.org/dwc/terms/group"/>
    <field index="37" term="http://portal.idigbio.org/terms/hasImage"/>
    <field index="38" term="http://portal.idigbio.org/terms/hasMedia"/>
    <field index="39" term="http://rs.tdwg.org/dwc/terms/higherClassification"/>
    <field index="40" term="http://rs.tdwg.org/dwc/terms/individualCount"/>
    <field index="41" term="http://rs.tdwg.org/dwc/terms/infraspecificEpithet"/>
    <field index="42" term="http://rs.tdwg.org/dwc/terms/institutionCode"/>
    <field index="43" term="http://rs.tdwg.org/dwc/terms/institutionID"/>
    <field index="44" term="http://portal.idigbio.org/terms/institutionName"/>
    <field index="45" term="http://rs.tdwg.org/dwc/terms/kingdom"/>
    <field index="46" term="http://rs.tdwg.org/dwc/terms/latestAgeOrHighestStage"/>
    <field index="47" term="http://rs.tdwg.org/dwc/terms/latestEpochOrHighestSeries"/>
    <field index="48" term="http://rs.tdwg.org/dwc/terms/latestEraOrHighestErathem"/>
    <field index="49" term="http://rs.tdwg.org/dwc/terms/latestPeriodOrHighestSystem"/>
    <field index="50" term="http://rs.tdwg.org/dwc/terms/lithostratigraphicTerms"/>
    <field index="51" term="http://rs.tdwg.org/dwc/terms/locality"/>
    <field index="52" term="http://rs.tdwg.org/dwc/terms/lowestBiostratigraphicZone"/>
    <field index="53" term="http://rs.tdwg.org/dwc/terms/maximumDepthInMeters"/>
    <field index="54" term="http://rs.tdwg.org/dwc/terms/maximumElevationInMeters"/>
    <field index="55" term="http://portal.idigbio.org/terms/mediarecords"/>
    <field index="56" term="http://rs.tdwg.org/dwc/terms/member"/>
    <field index="57" term="http://rs.tdwg.org/dwc/terms/minimumDepthInMeters"/>
    <field index="58" term="http://rs.tdwg.org/dwc/terms/minimumElevationInMeters"/>
    <field index="59" term="http://rs.tdwg.org/dwc/terms/municipality"/>
    <field index="60" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field index="61" term="http://rs.tdwg.org/dwc/terms/order"/>
    <field index="62" term="http://rs.tdwg.org/dwc/terms/phylum"/>
    <field index="63" term="http://portal.idigbio.org/terms/recordIds"/>
    <field index="64" term="http://rs.tdwg.org/dwc/terms/recordNumber"/>
    <field index="65" term="http://portal.idigbio.org/terms/recordset"/>
    <field index="66" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="67" term="http://rs.tdwg.org/dwc/terms/specificEpithet"/>
    <field index="68" term="http://rs.tdwg.org/dwc/terms/startDayOfYear"/>
    <field index="69" term="http://rs.tdwg.org/dwc/terms/stateProvince"/>
    <field index="70" term="http://rs.tdwg.org/dwc/terms/typeStatus"/>
    <field index="71" term="http://portal.idigbio.org/terms/uuid"/>
    <field index="72" term="http://rs.tdwg.org/dwc/terms/verbatimEventDate"/>
    <field index="73" term="http://rs.tdwg.org/dwc/terms/verbatimLocality"/>
    <field index="74" term="http://portal.idigbio.org/terms/version"/>
    <field index="75" term="http://rs.tdwg.org/dwc/terms/waterBody"/>

  </core>

  <extension encoding="utf-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/ac/terms/multimedia">
    <files>
      <location>multimedia_raw.csv</location>
    </files>
    <coreid index="0" />
    <field index="1" term="http://iptc.org/std/Iptc4xmpExt/2008-02-29/CountryName"/>
    <field index="2" term="http://iptc.org/std/Iptc4xmpExt/2008-02-29/CreditLine"/>
    <field index="3" term="http://rs.tdwg.org/ac/terms/accessURI"/>
    <field index="4" term="http://rs.tdwg.org/ac/terms/associatedSpecimenReference"/>
    <field index="5" term="http://rs.tdwg.org/ac/terms/attributionLogoURL"/>
    <field index="6" term="http://rs.tdwg.org/ac/terms/bestQualityAccessURI"/>
    <field index="7" term="http://rs.tdwg.org/ac/terms/bestQualityFormat"/>
    <field index="8" term="http://rs.tdwg.org/ac/terms/bestQualityVariantDescription"/>
    <field index="9" term="http://rs.tdwg.org/ac/terms/caption"/>
    <field index="10" term="http://rs.tdwg.org/ac/terms/captureDevice"/>
    <field index="11" term="http://rs.tdwg.org/ac/terms/comments"/>
    <field index="12" term="http://rs.tdwg.org/ac/terms/furtherInformationURL"/>
    <field index="13" term="http://rs.tdwg.org/ac/terms/goodQualityAccessURI"/>
    <field index="14" term="http://rs.tdwg.org/ac/terms/hashFunction"/>
    <field index="15" term="http://rs.tdwg.org/ac/terms/hashValue"/>
    <field index="16" term="http://rs.tdwg.org/ac/terms/licenseLogoURL"/>
    <field index="17" term="http://rs.tdwg.org/ac/terms/metadataCreator"/>
    <field index="18" term="http://rs.tdwg.org/ac/terms/metadataLanguage"/>
    <field index="19" term="http://rs.tdwg.org/ac/terms/metadataLanguageLiteral"/>
    <field index="20" term="http://rs.tdwg.org/ac/terms/metadataProvider"/>
    <field index="21" term="http://rs.tdwg.org/ac/terms/provider"/>
    <field index="22" term="http://rs.tdwg.org/ac/terms/providerLiteral"/>
    <field index="23" term="http://rs.tdwg.org/ac/terms/providerManagedID"/>
    <field index="24" term="http://rs.tdwg.org/ac/terms/resourceCreationTechnique"/>
    <field index="25" term="http://rs.tdwg.org/ac/terms/serviceExpectation"/>
    <field index="26" term="http://rs.tdwg.org/ac/terms/subjectOrientation"/>
    <field index="27" term="http://rs.tdwg.org/ac/terms/subjectPart"/>
    <field index="28" term="http://rs.tdwg.org/ac/terms/subtype"/>
    <field index="29" term="http://rs.tdwg.org/ac/terms/subtypeLiteral"/>
    <field index="30" term="http://rs.tdwg.org/ac/terms/tag"/>
    <field index="31" term="http://rs.tdwg.org/ac/terms/thumbnailAccessURI"/>
    <field index="32" term="http://rs.tdwg.org/ac/terms/variantLiteral"/>
    <field index="33" term="http://purl.org/dc/elements/1.1/creator"/>
    <field index="34" term="http://purl.org/dc/elements/1.1/format"/>
    <field index="35" term="http://purl.org/dc/elements/1.1/rights"/>
    <field index="36" term="http://purl.org/dc/elements/1.1/type"/>
    <field index="37" term="http://purl.org/dc/terms/accessRights"/>
    <field index="38" term="http://purl.org/dc/terms/available"/>
    <field index="39" term="http://purl.org/dc/terms/created"/>
    <field index="40" term="http://purl.org/dc/terms/creator"/>
    <field index="41" term="http://purl.org/dc/terms/description"/>
    <field index="42" term="http://purl.org/dc/terms/format"/>
    <field index="43" term="http://purl.org/dc/terms/identifier"/>
    <field index="44" term="http://purl.org/dc/terms/license"/>
    <field index="45" term="http://purl.org/dc/terms/modified"/>
    <field index="46" term="http://purl.org/dc/terms/provider"/>
    <field index="47" term="http://purl.org/dc/terms/publisher"/>
    <field index="48" term="http://purl.org/dc/terms/references"/>
    <field index="49" term="http://purl.org/dc/terms/rights"/>
    <field index="50" term="http://purl.org/dc/terms/rightsHolder"/>
    <field index="51" term="http://purl.org/dc/terms/source"/>
    <field index="52" term="http://purl.org/dc/terms/title"/>
    <field index="53" term="http://purl.org/dc/terms/type"/>
    <field index="54" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="55" term="http://ns.adobe.com/exif/1.0/PixelXDimension"/>
    <field index="56" term="http://ns.adobe.com/exif/1.0/PixelYDimension"/>
    <field index="57" term="http://portal.idigbio.org/terms/associatedRecordReference"/>
    <field index="58" term="http://portal.idigbio.org/terms/associatedRecordsetReference"/>
    <field index="59" term="http://portal.idigbio.org/terms/recordId"/>
    <field index="60" term="http://ns.adobe.com/photoshop/1.0/Credit"/>
    <field index="61" term="http://ns.adobe.com/xap/1.0/CreateDate"/>
    <field index="62" term="http://ns.adobe.com/xap/1.0/MetadataDate"/>
    <field index="63" term="http://ns.adobe.com/xap/1.0/rights/Owner"/>
    <field index="64" term="http://ns.adobe.com/xap/1.0/rights/UsageTerms"/>
    <field index="65" term="http://ns.adobe.com/xap/1.0/rights/WebStatement"/>

  </extension>

  <extension encoding="utf-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/ac/terms/multimedia">
    <files>
      <location>multimedia.csv</location>
    </files>
    <coreid index="0" />
    <field index="1" term="http://rs.tdwg.org/ac/terms/accessURI"/>
    <field index="2" term="http://portal.idigbio.org/terms/dateModified"/>
    <field index="3" term="http://portal.idigbio.org/terms/dataQualityScore"/>
    <field index="4" term="http://portal.idigbio.org/terms/etag"/>
    <field index="5" term="http://portal.idigbio.org/terms/flags"/>
    <field index="6" term="http://purl.org/dc/terms/format"/>
    <field index="7" term="http://portal.idigbio.org/terms/hasSpecimen"/>
    <field index="8" term="http://rs.tdwg.org/ac/terms/licenseLogoURL"/>
    <field index="9" term="http://portal.idigbio.org/terms/mediaType"/>
    <field index="10" term="http://purl.org/dc/terms/modified"/>
    <field index="11" term="http://portal.idigbio.org/terms/recordIds"/>
    <field index="12" term="http://portal.idigbio.org/terms/records"/>
    <field index="13" term="http://portal.idigbio.org/terms/recordsets"/>
    <field index="14" term="http://purl.org/dc/terms/rights"/>
    <field index="15" term="http://rs.tdwg.org/ac/terms/tag"/>
    <field index="16" term="http://purl.org/dc/elements/1.1/type"/>
    <field index="17" term="http://portal.idigbio.org/terms/uuid"/>
    <field index="18" term="http://portal.idigbio.org/terms/version"/>
    <field index="19" term="http://ns.adobe.com/xap/1.0/rights/WebStatement"/>
    <field index="20" term="http://ns.adobe.com/exif/1.0/PixelXDimension"/>
    <field index="21" term="http://ns.adobe.com/exif/1.0/PixelYDimension"/>

  </extension>

  <extension encoding="utf-8" fieldsTerminatedBy="," linesTerminatedBy="\n" fieldsEnclosedBy="&quot;" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files>
      <location>occurrence_raw.csv</location>
    </files>
    <coreid index="0" />
    <field index="1" term="http://purl.org/dc/elements/1.1/rights"/>
    <field index="2" term="http://purl.org/dc/terms/accessRights"/>
    <field index="3" term="http://purl.org/dc/terms/bibliographicCitation"/>
    <field index="4" term="http://purl.org/dc/terms/language"/>
    <field index="5" term="http://purl.org/dc/terms/license"/>
    <field index="6" term="http://purl.org/dc/terms/modified"/>
    <field index="7" term="http://purl.org/dc/terms/references"/>
    <field index="8" term="http://purl.org/dc/terms/rights"/>
    <field index="9" term="http://purl.org/dc/terms/rightsHolder"/>
    <field index="10" term="http://purl.org/dc/terms/source"/>
    <field index="11" term="http://purl.org/dc/terms/type"/>
    <field index="12" term="http://rs.tdwg.org/dwc/terms/Identification"/>
    <field index="13" term="http://rs.tdwg.org/dwc/terms/MeasurementOrFact"/>
    <field index="14" term="http://rs.tdwg.org/dwc/terms/ResourceRelationship"/>
    <field index="15" term="http://rs.tdwg.org/dwc/terms/VerbatimEventDate"/>
    <field index="16" term="http://rs.tdwg.org/dwc/terms/accessRights"/>
    <field index="17" term="http://rs.tdwg.org/dwc/terms/associatedMedia"/>
    <field index="18" term="http://rs.tdwg.org/dwc/terms/associatedOccurrences"/>
    <field index="19" term="http://rs.tdwg.org/dwc/terms/associatedReferences"/>
    <field index="20" term="http://rs.tdwg.org/dwc/terms/associatedSequences"/>
    <field index="21" term="http://rs.tdwg.org/dwc/terms/associatedTaxa"/>
    <field index="22" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
    <field index="23" term="http://rs.tdwg.org/dwc/terms/bed"/>
    <field index="24" term="http://rs.tdwg.org/dwc/terms/behavior"/>
    <field index="25" term="http://rs.tdwg.org/dwc/terms/catalogNumber"/>
    <field index="26" term="http://rs.tdwg.org/dwc/terms/class"/>
    <field index="27" term="http://rs.tdwg.org/dwc/terms/collectionCode"/>
    <field index="28" term="http://rs.tdwg.org/dwc/terms/collectionID"/>
    <field index="29" term="http://rs.tdwg.org/dwc/terms/continent"/>
    <field index="30" term="http://rs.tdwg.org/dwc/terms/coordinatePrecision"/>
    <field index="31" term="http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters"/>
    <field index="32" term="http://rs.tdwg.org/dwc/terms/country"/>
    <field index="33" term="http://rs.tdwg.org/dwc/terms/countryCode"/>
    <field index="34" term="http://rs.tdwg.org/dwc/terms/county"/>
    <field index="35" term="http://rs.tdwg.org/dwc/terms/dataGeneralizations"/>
    <field index="36" term="http://rs.tdwg.org/dwc/terms/datasetID"/>
    <field index="37" term="http://rs.tdwg.org/dwc/terms/datasetName"/>
    <field index="38" term="http://rs.tdwg.org/dwc/terms/dateIdentified"/>
    <field index="39" term="http://rs.tdwg.org/dwc/terms/day"/>
    <field index="40" term="http://rs.tdwg.org/dwc/terms/decimalLatitude"/>
    <field index="41" term="http://rs.tdwg.org/dwc/terms/decimalLongitude"/>
    <field index="42" term="http://rs.tdwg.org/dwc/terms/disposition"/>
    <field index="43" term="http://rs.tdwg.org/dwc/terms/dynamicProperties"/>
    <field index="44" term="http://rs.tdwg.org/dwc/terms/earliestAgeOrLowestStage"/>
    <field index="45" term="http://rs.tdwg.org/dwc/terms/earliestEonOrLowestEonothem"/>
    <field index="46" term="http://rs.tdwg.org/dwc/terms/earliestEpochOrLowestSeries"/>
    <field index="47" term="http://rs.tdwg.org/dwc/terms/earliestEraOrLowestErathem"/>
    <field index="48" term="http://rs.tdwg.org/dwc/terms/earliestPeriodOrLowestSystem"/>
    <field index="49" term="http://rs.tdwg.org/dwc/terms/endDayOfYear"/>
    <field index="50" term="http://rs.tdwg.org/dwc/terms/establishmentMeans"/>
    <field index="51" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
    <field index="52" term="http://rs.tdwg.org/dwc/terms/eventID"/>
    <field index="53" term="http://rs.tdwg.org/dwc/terms/eventRemarks"/>
    <field index="54" term="http://rs.tdwg.org/dwc/terms/eventTime"/>
    <field index="55" term="http://rs.tdwg.org/dwc/terms/family"/>
    <field index="56" term="http://rs.tdwg.org/dwc/terms/fieldNotes"/>
    <field index="57" term="http://rs.tdwg.org/dwc/terms/fieldNumber"/>
    <field index="58" term="http://rs.tdwg.org/dwc/terms/footprintWKT"/>
    <field index="59" term="http://rs.tdwg.org/dwc/terms/formation"/>
    <field index="60" term="http://rs.tdwg.org/dwc/terms/genus"/>
    <field index="61" term="http://rs.tdwg.org/dwc/terms/geodeticDatum"/>
    <field index="62" term="http://rs.tdwg.org/dwc/terms/geologicalContextID"/>
    <field index="63" term="http://rs.tdwg.org/dwc/terms/georeferenceProtocol"/>
    <field index="64" term="http://rs.tdwg.org/dwc/terms/georeferenceRemarks"/>
    <field index="65" term="http://rs.tdwg.org/dwc/terms/georeferenceSources"/>
    <field index="66" term="http://rs.tdwg.org/dwc/terms/georeferenceVerificationStatus"/>
    <field index="67" term="http://rs.tdwg.org/dwc/terms/georeferencedBy"/>
    <field index="68" term="http://rs.tdwg.org/dwc/terms/georeferencedDate"/>
    <field index="69" term="http://rs.tdwg.org/dwc/terms/group"/>
    <field index="70" term="http://rs.tdwg.org/dwc/terms/habitat"/>
    <field index="71" term="http://rs.tdwg.org/dwc/terms/higherClassification"/>
    <field index="72" term="http://rs.tdwg.org/dwc/terms/higherGeography"/>
    <field index="73" term="http://rs.tdwg.org/dwc/terms/higherGeographyID"/>
    <field index="74" term="http://rs.tdwg.org/dwc/terms/highestBiostratigraphicZone"/>
    <field index="75" term="http://rs.tdwg.org/dwc/terms/identificationID"/>
    <field index="76" term="http://rs.tdwg.org/dwc/terms/identificationQualifier"/>
    <field index="77" term="http://rs.tdwg.org/dwc/terms/identificationReferences"/>
    <field index="78" term="http://rs.tdwg.org/dwc/terms/identificationRemarks"/>
    <field index="79" term="http://rs.tdwg.org/dwc/terms/identificationVerificationStatus"/>
    <field index="80" term="http://rs.tdwg.org/dwc/terms/identifiedBy"/>
    <field index="81" term="http://rs.tdwg.org/dwc/terms/individualCount"/>
    <field index="82" term="http://rs.tdwg.org/dwc/terms/individualID"/>
    <field index="83" term="http://rs.tdwg.org/dwc/terms/informationWithheld"/>
    <field index="84" term="http://rs.tdwg.org/dwc/terms/infraspecificEpithet"/>
    <field index="85" term="http://rs.tdwg.org/dwc/terms/institutionCode"/>
    <field index="86" term="http://rs.tdwg.org/dwc/terms/institutionID"/>
    <field index="87" term="http://rs.tdwg.org/dwc/terms/island"/>
    <field index="88" term="http://rs.tdwg.org/dwc/terms/islandGroup"/>
    <field index="89" term="http://rs.tdwg.org/dwc/terms/kingdom"/>
    <field index="90" term="http://rs.tdwg.org/dwc/terms/latestAgeOrHighestStage"/>
    <field index="91" term="http://rs.tdwg.org/dwc/terms/latestEonOrHighestEonothem"/>
    <field index="92" term="http://rs.tdwg.org/dwc/terms/latestEpochOrHighestSeries"/>
    <field index="93" term="http://rs.tdwg.org/dwc/terms/latestEraOrHighestErathem"/>
    <field index="94" term="http://rs.tdwg.org/dwc/terms/latestPeriodOrHighestSystem"/>
    <field index="95" term="http://rs.tdwg.org/dwc/terms/lifeStage"/>
    <field index="96" term="http://rs.tdwg.org/dwc/terms/lithostratigraphicTerms"/>
    <field index="97" term="http://rs.tdwg.org/dwc/terms/locality"/>
    <field index="98" term="http://rs.tdwg.org/dwc/terms/locationAccordingTo"/>
    <field index="99" term="http://rs.tdwg.org/dwc/terms/locationID"/>
    <field index="100" term="http://rs.tdwg.org/dwc/terms/locationRemarks"/>
    <field index="101" term="http://rs.tdwg.org/dwc/terms/lowestBiostratigraphicZone"/>
    <field index="102" term="http://rs.tdwg.org/dwc/terms/maximumDepthInMeters"/>
    <field index="103" term="http://rs.tdwg.org/dwc/terms/maximumElevationInMeters"/>
    <field index="104" term="http://rs.tdwg.org/dwc/terms/member"/>
    <field index="105" term="http://rs.tdwg.org/dwc/terms/minimumDepthInMeters"/>
    <field index="106" term="http://rs.tdwg.org/dwc/terms/minimumElevationInMeters"/>
    <field index="107" term="http://rs.tdwg.org/dwc/terms/month"/>
    <field index="108" term="http://rs.tdwg.org/dwc/terms/municipality"/>
    <field index="109" term="http://rs.tdwg.org/dwc/terms/nameAccordingTo"/>
    <field index="110" term="http://rs.tdwg.org/dwc/terms/namePublishedIn"/>
    <field index="111" term="http://rs.tdwg.org/dwc/terms/namePublishedInID"/>
    <field index="112" term="http://rs.tdwg.org/dwc/terms/namePublishedInYear"/>
    <field index="113" term="http://rs.tdwg.org/dwc/terms/nomenclaturalCode"/>
    <field index="114" term="http://rs.tdwg.org/dwc/terms/nomenclaturalStatus"/>
    <field index="115" term="http://rs.tdwg.org/dwc/terms/occurrenceDetails"/>
    <field index="116" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field index="117" term="http://rs.tdwg.org/dwc/terms/occurrenceRemarks"/>
    <field index="118" term="http://rs.tdwg.org/dwc/terms/occurrenceStatus"/>
    <field index="119" term="http://rs.tdwg.org/dwc/terms/order"/>
    <field index="120" term="http://rs.tdwg.org/dwc/terms/organismRemarks"/>
    <field index="121" term="http://rs.tdwg.org/dwc/terms/originalNameUsage"/>
    <field index="122" term="http://rs.tdwg.org/dwc/terms/otherCatalogNumbers"/>
    <field index="123" term="http://rs.tdwg.org/dwc/terms/ownerInstitutionCode"/>
    <field index="124" term="http://rs.tdwg.org/dwc/terms/parentNameUsage"/>
    <field index="125" term="http://rs.tdwg.org/dwc/terms/phylum"/>
    <field index="126" term="http://rs.tdwg.org/dwc/terms/preparations"/>
    <field index="127" term="http://rs.tdwg.org/dwc/terms/previousIdentifications"/>
    <field index="128" term="http://rs.tdwg.org/dwc/terms/recordNumber"/>
    <field index="129" term="http://rs.tdwg.org/dwc/terms/recordedBy"/>
    <field index="130" term="http://rs.tdwg.org/dwc/terms/relatedResourceID"/>
    <field index="131" term="http://rs.tdwg.org/dwc/terms/reproductiveCondition"/>
    <field index="132" term="http://rs.tdwg.org/dwc/terms/rights"/>
    <field index="133" term="http://rs.tdwg.org/dwc/terms/rightsHolder"/>
    <field index="134" term="http://rs.tdwg.org/dwc/terms/samplingEffort"/>
    <field index="135" term="http://rs.tdwg.org/dwc/terms/samplingProtocol"/>
    <field index="136" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="137" term="http://rs.tdwg.org/dwc/terms/scientificNameAuthorship"/>
    <field index="138" term="http://rs.tdwg.org/dwc/terms/scientificNameID"/>
    <field index="139" term="http://rs.tdwg.org/dwc/terms/sex"/>
    <field index="140" term="http://rs.tdwg.org/dwc/terms/specificEpithet"/>
    <field index="141" term="http://rs.tdwg.org/dwc/terms/startDayOfYear"/>
    <field index="142" term="http://rs.tdwg.org/dwc/terms/stateProvince"/>
    <field index="143" term="http://rs.tdwg.org/dwc/terms/subgenus"/>
    <field index="144" term="http://rs.tdwg.org/dwc/terms/taxonID"/>
    <field index="145" term="http://rs.tdwg.org/dwc/terms/taxonRank"/>
    <field index="146" term="http://rs.tdwg.org/dwc/terms/taxonRemarks"/>
    <field index="147" term="http://rs.tdwg.org/dwc/terms/taxonomicStatus"/>
    <field index="148" term="http://rs.tdwg.org/dwc/terms/typeStatus"/>
    <field index="149" term="http://rs.tdwg.org/dwc/terms/verbatimCoordinateSystem"/>
    <field index="150" term="http://rs.tdwg.org/dwc/terms/verbatimCoordinates"/>
    <field index="151" term="http://rs.tdwg.org/dwc/terms/verbatimDepth"/>
    <field index="152" term="http://rs.tdwg.org/dwc/terms/verbatimElevation"/>
    <field index="153" term="http://rs.tdwg.org/dwc/terms/verbatimEventDate"/>
    <field index="154" term="http://rs.tdwg.org/dwc/terms/verbatimLatitude"/>
    <field index="155" term="http://rs.tdwg.org/dwc/terms/verbatimLocality"/>
    <field index="156" term="http://rs.tdwg.org/dwc/terms/verbatimLongitude"/>
    <field index="157" term="http://rs.tdwg.org/dwc/terms/verbatimSRS"/>
    <field index="158" term="http://rs.tdwg.org/dwc/terms/verbatimTaxonRank"/>
    <field index="159" term="http://rs.tdwg.org/dwc/terms/vernacularName"/>
    <field index="160" term="http://rs.tdwg.org/dwc/terms/waterBody"/>
    <field index="161" term="http://rs.tdwg.org/dwc/terms/year"/>
    <field index="162" term="http://portal.idigbio.org/terms/fcc/datePicked"/>
    <field index="163" term="http://portal.idigbio.org/terms/fcc/pickedBy"/>
    <field index="164" term="http://rs.gbif.org/terms/1.0/Reference"/>
    <field index="165" term="http://portal.idigbio.org/terms/associatedFamily"/>
    <field index="166" term="http://portal.idigbio.org/terms/associatedRelationship"/>
    <field index="167" term="http://portal.idigbio.org/terms/preparationCount"/>
    <field index="168" term="http://portal.idigbio.org/terms/preservative"/>
    <field index="169" term="http://portal.idigbio.org/terms/recordId"/>
    <field index="170" term="http://portal.idigbio.org/terms/subfamily"/>
    <field index="171" term="http://portal.idigbio.org/terms/substrate"/>
    <field index="172" term="http://portal.idigbio.org/terms/superfamily"/>
    <field index="173" term="http://portal.idigbio.org/terms/inhs/dead"/>
    <field index="174" term="http://portal.idigbio.org/terms/inhs/formII_females"/>
    <field index="175" term="http://portal.idigbio.org/terms/inhs/formII_males"/>
    <field index="176" term="http://portal.idigbio.org/terms/inhs/formI_males"/>
    <field index="177" term="http://portal.idigbio.org/terms/inhs/instars_Female"/>
    <field index="178" term="http://portal.idigbio.org/terms/inhs/instars_Male"/>
    <field index="179" term="http://portal.idigbio.org/terms/inhs/juv_females"/>
    <field index="180" term="http://portal.idigbio.org/terms/inhs/juv_males"/>
    <field index="181" term="http://portal.idigbio.org/terms/inhs/juv_undetermined"/>
    <field index="182" term="http://portal.idigbio.org/terms/inhs/live"/>
    <field index="183" term="http://portal.idigbio.org/terms/inhs/location_Basin"/>
    <field index="184" term="http://portal.idigbio.org/terms/inhs/location_RiverMile"/>
    <field index="185" term="http://portal.idigbio.org/terms/inhs/location_Stream"/>
    <field index="186" term="http://portal.idigbio.org/terms/inhs/relic"/>
    <field index="187" term="http://portal.idigbio.org/terms/inhs/total_Males"/>
    <field index="188" term="http://portal.idigbio.org/terms/inhs/total_females"/>
    <field index="189" term="http://portal.idigbio.org/terms/inhs/vouchered"/>
    <field index="190" term="http://symbiota.org/terms/recordEnteredBy"/>
    <field index="191" term="http://symbiota.org/terms/verbatimScientificName"/>

  </extension>

</archive>
```

**Comment by godfoder** [comment]
I'm building a new dump file now. So hopefully this should be ready for testing in a day or so.

**Comment by jhpoelen** [comment]
Thanks! Just re-ran the import (started 9:27p Florida time), and I think the changes have not yet propagated. I'll try again some time tomorrow.

**Comment by godfoder** [comment]
The dump file is still generating, we had some network instability that torpedoed the first run, then I ran a server out of disk space...

**Comment by jhpoelen** [comment]
thanks for update! standing by . . .

**Comment by godfoder** [comment]
This should be up to date now, go ahead and give it a whirl.

**Comment by jhpoelen** [comment]
thanks! I gave it a wirl (see http://archive.effechecka.org/job/idigbio/6/) and there seems to be a access issue. 

`wget --quiet https://s.idigbio.org/idigbio-static-downloads/idigbio.zip -O tmp.zip` says:

``` xml
<Error>
<Code>AccessDenied</Code>
<BucketName>idigbio-static-downloads</BucketName>
<RequestId>tx00000000000000026092d-0057cef537-aefac-default</RequestId>
<HostId>aefac-default-default</HostId>
</Error>
```

**Comment by jhpoelen** [comment]
@godfoder idigbio import is still failing with access issue. Any chance you can fix this before the summit?

**Comment by jhpoelen** [comment]
import success (see image below). 

Thanks @godfoder for fixing the issue.

![image](https://cloud.githubusercontent.com/assets/1084872/18934395/4ecb1534-858e-11e6-87eb-0e7425a37e6e.png)
